DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    author VARCHAR(512) NOT NULL,
    title VARCHAR(512) NOT NULL,
    genre VARCHAR(512) NOT NULL,
    pages INTEGER NOT NULL,
    quantity INTEGER CHECK (quantity > 0)  
);